// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using DataAccess.Interfaces;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.Models;

[Index("CategoryId", Name = "IX_Brands_CategoryId")]
public partial class Brand : ISoftDeletable
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(255)]
    public string Name_Local { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Name_Global { get; set; }

    public string Description_Local { get; set; }

    [Unicode(false)]
    public string Description_Global { get; set; }


    public string Logo { get; set; }

    public string LogoUrl { get; set; }

	public int CategoryId { get; set; }

    //public bool IsDeleted { get; set; }

    [ForeignKey("CategoryId")]
    [InverseProperty("Brands")]
    public virtual Category Category { get; set; }

    [InverseProperty("Brand")]
    public virtual ICollection<Product> Products { get; set; } = new List<Product>();

   // public virtual ICollection<PaidProduct> PaidProducts { get; set; }

}