// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using DataAccess.Interfaces;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.Models;

[Table("ProductSponsored")]
[Index("ProdDetId", Name = "IX_ProductSponsored_ProdId")]
public partial class ProductSponsored : ISoftDeletable
{
    [Key]
    public int Id { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Cost { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime StartDate { get; set; }

    public int Duration { get; set; }

    public int ProdDetId { get; set; }

    [ForeignKey("ProdDetId")]
    [InverseProperty("ProductSponsoreds")]
    public virtual ProductDetail ProdDet { get; set; }
}