// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using DataAccess.Interfaces;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.Models;

[Table("Product")]
[Index("BrandId", Name = "IX_Product_BrandId")]
[Index("SubCategoryId", Name = "IX_Product_SubCategoryId")]
public partial class Product : ISoftDeletable
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(255)]
    public string Name_Local { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Name_Global { get; set; }

    public string Description_Local { get; set; }

    [Unicode(false)]
    public string Description_Global { get; set; }

    public int SubCategoryId { get; set; }

    
    public int? BrandId { get; set; }

    public int NumberOfClicks { get; set; } = 0;

    [ForeignKey("BrandId")]
    [InverseProperty("Products")]
    public virtual Brand Brand { get; set; }

    [InverseProperty("Prod")]
    public virtual ICollection<PriceHistory> PriceHistories { get; set; } = new List<PriceHistory>();

    [InverseProperty("Prod")]
    public virtual ICollection<ProductImage> ProductImages { get; set; } = new List<ProductImage>();

    [InverseProperty("Prod")]
    public virtual ICollection<ProductLink> ProductLinks { get; set; } = new List<ProductLink>();

    [ForeignKey("SubCategoryId")]
    [InverseProperty("Products")]
    public virtual SubCategory SubCategory { get; set; }

    //[ForeignKey("ProdId")]
    //[InverseProperty("ProdAlertUser")]
    //public virtual ICollection<User> UserAlertProd { get; set; } = new List<User>();

    //[ForeignKey("ProdId")]
    //[InverseProperty("ProdHistoryUser")]
    //public virtual ICollection<User> UserHistoryProd { get; set; } = new List<User>();

    //[ForeignKey("ProdId")]
    //[InverseProperty("ProdFavUser")]
    //public virtual ICollection<User> UserFavProd { get; set; } = new List<User>();

    // test
    //[ForeignKey("ProdId")]
    //[InverseProperty("ProdAlertUser")]
    public virtual ICollection<UserAlertProd> UserAlertProds { get; set; } = new List<UserAlertProd>();
    //[ForeignKey("ProdId")]
    //[InverseProperty("ProdHistoryUser")]
    public virtual ICollection<UserHistoryProd> UserHistoryProds { get; set; } = new List<UserHistoryProd>();
    //[ForeignKey("ProdId")]
    //[InverseProperty("ProdFavUser")]
    public virtual ICollection<UserFavProd> UserFavProds { get; set; } = new List<UserFavProd>();
}