// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DataAccess.Interfaces;

namespace DataAccess.Models
{
    public class UserAlertProd : ISoftDeletable
    {
        public int UserID { get; set; }
        public int ProductId { get; set; }
        public virtual User User { get; set; }
        public virtual Product Product { get; set; }
    }
}