// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

using Microsoft.AspNetCore.Identity;

using DataAccess.Interfaces;

using Microsoft.EntityFrameworkCore;

namespace DataAccess.Models;


//[Index("Email", Name = "UQ__Users__A9D10534A011E897", IsUnique = true)]

public partial class User : ISoftDeletable
{
    [Key]
    public int Id { get; set; }

    public virtual AuthUser AuthenticatedUser { get; set; }

    [ForeignKey("AuthenticatedUser")]
    public string AuthUserID { get; set; }


    [InverseProperty("User")]
    public virtual ICollection<SearchValue> SearchValues { get; set; } = new List<SearchValue>();

    [ForeignKey("UserID")]
    [InverseProperty("UserAlertProd")]
    public virtual ICollection<Product> ProdAlertUser { get; set; } = new List<Product>();

    [ForeignKey("UserID")]
    [InverseProperty("UserHistoryProd")]
    public virtual ICollection<Product> ProdHistoryUser { get; set; } = new List<Product>();

    [ForeignKey("UserID")]
    [InverseProperty("UserFavProd")]
    public virtual ICollection<Product> ProdFavUser { get; set; } = new List<Product>();

}